In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Untitled Folder/customer_shopping_behavior.csv')

In [3]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
##including categorical values
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
##Median categorical imputation of missing values > Overall Median imputation thus 
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
##Convert everything to snake case for sql and python coding efficiency

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})
df = df.rename(columns={'age_group':'age'})

In [12]:
#neat and consitent columns good for coding
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [14]:
#create a column age group
labels = ['young_adult','adult','middle_aged','senior']
df['age_group'] = pd.qcut(df['age'],q = 4 ,labels = labels)

In [15]:
df[['age','age_group']].head(10)

   age    age_group
0   55  middle_aged
1   19  young_adult
2   50  middle_aged
3   21  young_adult
4   45  middle_aged
5   46  middle_aged
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle_aged

In [16]:
##create purchase_frequency_days in texttual fs to numericals fs
frequency_mapping = {

     'Weekly' : 14,
     'Fortnightly' : 14,
     'Bi-Weekly' : 14,
     'Monthly' : 30,
     'Quarterly' : 90,
     'Every 3 Months' : 90,
     'Annually' : 365

}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                       14                 Weekly
3                       14                 Weekly
4                      365               Annually
5                       14                 Weekly
6                       90              Quarterly
7                       14                 Weekly
8                      365               Annually
9                       90              Quarterly

In [18]:
#there are cases when promo codes are nit use and discounts still applied

(df['discount_applied'] == df['promo_code_used']).all()

True

In [19]:
##since its true lets just get rid of the other column promo_code_use.
df = df.drop('promo_code_used',axis = 1)

In [20]:
df = df.drop('frequency_of_purchases',axis = 1)

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [22]:
##CREATE DATABASE IN MYSQL
##CODE PIPELINE

#pip install sqlalchemy (for sql)
#pip install psycogp2 (for postgresql)
#pip install pymsql (for MySQL)
#pip install pyodbc (for MySQL server ie cloud based like Google Big Query) ... Prior cell 


# from sqalchemy import create_engine

#username = "MySQL" ## default user
#passsword = "xxxx" ##password set during installation
#host = "local host" ##if running locally
#port = "5432"  ##default MySQL port
#database = "FirstDAp.MySQL" ##database created in MySQL
#connection_string = 'mysql + pymsyql://username:password@localhost:3306/my_database'


#engine = create_engine(connection_string) -- initialized the connection_string

##MAGIC!!Sream the data to MySQL or dialect
#df.to_sql( name = '' -- name you want for the sql table \n , con = engine \n -- engine we created above ,
# if_exists = 'replace' -- use replace to fill in the data,
#index = False  -- set false so that the pandas row indeces arent saved as a column )

#printf("Data successfully into sql database!")

In [23]:
import os
from dotenv import load_dotenv

# Try to load the file explicitly
load_dotenv(dotenv_path="Untitled Folder/.env")

print("User:", repr(os.getenv("DB_USER")))
print("Host:", repr(os.getenv("DB_HOST")))
print("Port:", repr(os.getenv("DB_PORT")))
print("Database:", repr(os.getenv("DB_NAME")))

User: None
Host: None
Port: None
Database: None

In [24]:
pip install pandas sqlalchemy pymysql python-dotenv

Requirement already satisfied: pandas in c:\users\ianjo\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: sqlalchemy in c:\users\ianjo\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\ianjo\anaconda3\lib\site-packages (1.2.3)
Requirement already satisfied: python-dotenv in c:\users\ianjo\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ianjo\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ianjo\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ianjo\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ianjo\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ianjo\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ianjo\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\ianjo\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
%who DataFrame

df

In [26]:
import os
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from dotenv import load_dotenv

load_dotenv()

USER = "root"
PASSWORD = os.getenv("DB_PASSWORD")
HOST = "127.0.0.1"
PORT = 3306
DATABASE = "practice1"

connection_url = URL.create(
    drivername="mysql+pymysql",
    username=USER,
    password=PASSWORD,
    host=HOST,
    port=PORT,
    database=DATABASE,
)

engine = create_engine(connection_url)

df.to_sql(
    name="cleaned_customer_shopping_behaviour",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data successfully exported into your MySQL database!")

Data successfully exported into your MySQL database!

In [27]:
check = pd.read_sql("SELECT COUNT(*) AS row_count FROM cleaned_customer_shopping_behaviour", con=engine)
print(check)

check_head = pd.read_sql("SELECT * FROM cleaned_customer_shopping_behaviour LIMIT 5", con=engine)
check_head

   row_count
0       3900

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,middle_aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,young_adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,middle_aged,14
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,young_adult,14
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,middle_aged,365